# Generated by Django 6.0.7 on 2026-08-02 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('company', models.CharField(max_length=128)),
                ('date_applied', models.DateField()),
                ('state', models.IntegerField()),
                ('link', models.URLField()),
            ],
        ),
    ]
