# Generated by Django 6.0.7 on 2026-08-02 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='state',
            field=models.IntegerField(choices=[(0, 'Applied'), (1, 'Interviewing'), (2, 'Offered'), (3, 'Rejected')]),
        ),
    ]
