# Generated by Django 6.0.7 on 2026-08-02 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_applications_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('company', models.CharField(max_length=128)),
                ('date_applied', models.DateField()),
                ('state', models.CharField(choices=[('APPLIED', 'Applied'), ('INTERVIEWING', 'Interviewing'), ('OFFER', 'Offer'), ('REJECTED', 'Rejected')], max_length=128)),
                ('link', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='Applications',
        ),
    ]
